spring:
  datasource:
  #test数据库是用于测试
#    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false
  #ScJn
    url: jdbc:mysql://localhost:3306/etsys?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    #配置druid连接池
   # type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    # specify the database
    database: mysql
    # show the sql in log or not
    show-sql: true

    hibernate:
      # create table if there is no table corresponding to the Persistence class
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect # set the dialect
  #bean中有属性为空的时候会导致json格式转换失败
  jackson:
    serialization:
      fail-on-empty-beans: false
  session:
      store-type: none
      timeout: 72h
server:
  port: 8084


