spring:
  datasource:
    url: jdbc:mysql://localhost:3306/esystem?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    # specify the database
    database: mysql
    # show the sql in log or not
    show-sql: true

    hibernate:
      # create table if there is no table corresponding to the Persistence class
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5Dialect # set the dialect
server:
  port: 8084



